# Generated by Django 2.2.6 on 2019-10-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='initial_balance',
            field=models.IntegerField(verbose_name=0),
        ),
    ]
