# Generated by Django 2.2.6 on 2019-10-31 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_auto_20191101_0200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='initial_balance',
        ),
    ]
