# Generated by Django 2.2.6 on 2019-10-31 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0003_remove_customuser_initial_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='initial_balance',
            field=models.IntegerField(default=0),
        ),
    ]
