# Generated by Django 2.2.6 on 2019-11-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0004_customuser_initial_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='initial_balance',
            field=models.IntegerField(default=50000),
        ),
    ]
