# Generated by Django 2.2.6 on 2019-11-08 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0008_customuser_is_banned'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card1', models.ImageField(default='cards/default1.jpg', upload_to='cards')),
                ('card2', models.ImageField(default='cards/default2.jpg', upload_to='cards')),
                ('card3', models.ImageField(default='cards/default3.jpg', upload_to='cards')),
                ('card4', models.ImageField(default='cards/default4.jpg', upload_to='cards')),
            ],
        ),
    ]
