# Generated by Django 2.2.6 on 2019-11-09 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0009_cards'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cards',
            old_name='card1',
            new_name='foto',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='card2',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='card3',
        ),
        migrations.RemoveField(
            model_name='cards',
            name='card4',
        ),
        migrations.AddField(
            model_name='cards',
            name='dostoinstvo',
            field=models.CharField(default='Valet', max_length=100),
        ),
        migrations.AddField(
            model_name='cards',
            name='mast',
            field=models.CharField(default='Piki', max_length=100),
        ),
    ]
