# Generated by Django 2.2.6 on 2019-11-09 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0010_auto_20191109_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='o4ko',
            field=models.IntegerField(default=10),
        ),
    ]
