# Generated by Django 2.2.6 on 2019-11-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0011_cards_o4ko'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTslides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_i', models.IntegerField()),
                ('index_j', models.IntegerField()),
                ('slide', models.ImageField(upload_to='PTslides')),
            ],
        ),
    ]
