# Generated by Django 2.2.7 on 2019-12-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0013_rouletteslides'),
    ]

    operations = [
        migrations.AddField(
            model_name='rouletteslides',
            name='value',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
