# Generated by Django 2.2.7 on 2019-12-05 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0014_rouletteslides_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('elements_image', models.ImageField(upload_to='Slot_Elements')),
            ],
        ),
    ]
